### PR TITLE
Update and rename example.justlists.ts to tronconnect.justlists.ts

### PR DESCRIPTION
**Pull request by tronconnect2021**

### CODE REVIEW

**Comment by douglas777topearner** [comment]
I

**Comment by douglas777topearner** [comment]
778

**Comment by tronconnect2021** [comment]
We want to list our token in justswap

Tronconnect
Tronconnect.org
TCX

**Review by shchow107 — APPROVED** [review]
TWMUFkBnT8keic3oYVDp9urqP5x84RFD5o

**Review by sullltan123 — APPROVED** [review]

**Comment by tronconnect2021** [comment]
How to pull the request

**Pull request closed without merging**
